### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Xiao-Ann** [Wang-Tianwei/Decoupled-attention-network#6]
内存是够的，也试了网上针对RuntimeError: CUDA error: out of memory问题的方法，都无效，不知道有没有人知道是咋回事？感激不尽！
DTD(
  (pre_lstm): LSTM(256, 128, bidirectional=True)
  (rnn): GRUCell(512, 256)
  (generator): Sequential(
    (0): Dropout(p=0.7)
    (1): Linear(in_features=256, out_features=80, bias=True)
  )
)
error
error
preparing all done
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    test_acc_counter])
  File "main.py", line 105, in test
    features= model[0](data)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sun/sunny/projects/Decoupled-attention-network/DAN.py", line 20, in forward
    features = self.model(input)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sun/sunny/projects/Decoupled-attention-network/resnet.py", line 108, in forward
    x = self.layer3(x)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sun/sunny/projects/Decoupled-attention-network/resnet.py", line 30, in forward
    out = self.conv1(x)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sun/anaconda3/envs/DAN/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by Wang-Tianwei** [comment]
爆显存了吧，batch size改小点试试。也可以换更小的backbone

**Comment by Xiao-Ann** [comment]
@Wang-Tianwei 谢谢您！batch size改小就解决了！
